version: '3'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: movie_rate
      POSTGRES_USER: username
      POSTGRES_PASSWORD: mysecretpassword
    ports:
      - 5432:5432
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin@example.com
      PGADMIN_DEFAULT_PASSWORD: pgadminpassword
    ports:
      - 80:80