version: '3'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: movie_rate
      POSTGRES_USER: username
      POSTGRES_PASSWORD: mysecretpassword
    volumes:
      - ./local/data:/var/lib/postgresql/data
      - ./local/init-database.sql:/docker-entrypoint-initdb.d/init-database.sql
    ports:
      - "5432:5432"